# Generated by Django 5.2.8 on 2025-11-13 19:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmSound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название мелодии")),
                (
                    "file",
                    models.FileField(
                        upload_to="alarm_sounds/default/",
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=["mp3", "wav", "ogg"])
                        ],
                        verbose_name="Файл мелодии",
                    ),
                ),
                ("is_default", models.BooleanField(default=True, verbose_name="Стандартная мелодия")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "мелодия будильника",
                "verbose_name_plural": "мелодии будильников",
            },
        ),
        migrations.CreateModel(
            name="Alarm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название будильника")),
                ("reminder_text", models.TextField(blank=True, verbose_name="Текст напоминания")),
                ("alarm_time", models.TimeField(verbose_name="Время срабатывания")),
                ("is_recurring", models.BooleanField(default=False, verbose_name="Повторяющийся будильник")),
                ("days_of_week", models.JSONField(blank=True, default=list, verbose_name="Дни недели")),
                (
                    "custom_sound",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="alarm_sounds/custom/",
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=["mp3", "wav", "ogg"])
                        ],
                        verbose_name="Своя мелодия",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="alarms", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alarm.alarmsound", verbose_name="Мелодия"
                    ),
                ),
            ],
            options={
                "verbose_name": "будильник",
                "verbose_name_plural": "будильники",
                "ordering": ["alarm_time"],
            },
        ),
    ]
