# Generated by Django 5.2.8 on 2025-11-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_mediafile"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"file_type__startswith": "image"},
                related_name="diary_entries",
                to="diary.mediafile",
                verbose_name="images",
            ),
        ),
    ]
