# Generated by Django 5.2.8 on 2025-11-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_diaryentry_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(upload_to="uploads/%Y/%m/%d/"),
        ),
    ]
