# Generated by Django 5.2.8 on 2025-11-09 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "🔵 Низкий"), ("medium", "🟡 Средний"), ("high", "🔴 Высокий")],
                        default="medium",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "📝 К выполнению"),
                            ("in_progress", "🔄 В процессе"),
                            ("done", "✅ Выполнено"),
                        ],
                        default="todo",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True, verbose_name="Срок выполнения")),
                ("completed_date", models.DateTimeField(blank=True, null=True, verbose_name="Дата выполнения")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
    ]
