# Generated by Django 5.2.8 on 2025-11-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_notification_notificationpreference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="task",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notificationpreference",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="planner_tas_user_id_73a774_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="planner_tas_user_id_09183e_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="planner_tas_due_dat_0e83de_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="planner_tas_parent__a65fc2_idx",
        ),
        migrations.RemoveField(
            model_name="task",
            name="custom_notification_time",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="task",
            name="monthly_days",
        ),
        migrations.RemoveField(
            model_name="task",
            name="notification_setting",
        ),
        migrations.RemoveField(
            model_name="task",
            name="parent_task",
        ),
        migrations.RemoveField(
            model_name="task",
            name="recurrence_end_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="weekly_days",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="NotificationPreference",
        ),
    ]
