# Generated by Django 5.2.8 on 2025-11-13 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_remove_notification_task_remove_notification_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("deadline", "Приближается дедлайн"),
                            ("overdue", "Просроченная задача"),
                            ("reminder", "Напоминание"),
                            ("system", "Системное уведомление"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_for", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enable_email_notifications", models.BooleanField(default=True)),
                ("enable_push_notifications", models.BooleanField(default=True)),
                ("enable_browser_notifications", models.BooleanField(default=True)),
                ("notify_before_deadline", models.BooleanField(default=True)),
                (
                    "deadline_reminder_time",
                    models.PositiveIntegerField(default=24, help_text="За сколько часов уведомлять о дедлайне"),
                ),
                ("notify_on_overdue", models.BooleanField(default=True)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="custom_notification_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время уведомления"),
        ),
        migrations.AddField(
            model_name="task",
            name="is_recurring",
            field=models.CharField(
                choices=[
                    ("none", "Не повторяется"),
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                    ("custom", "Особое расписание"),
                ],
                default="none",
                max_length=20,
                verbose_name="Повторение",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="monthly_days",
            field=models.JSONField(
                blank=True, default=list, help_text="Числа месяца для повторения (1-31)", verbose_name="Числа месяца"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="notification_setting",
            field=models.CharField(
                choices=[
                    ("none", "Не уведомлять"),
                    ("day_before", "За день"),
                    ("hour_before", "За час"),
                    ("fifteen_minutes", "За 15 минут"),
                    ("at_time", "В указанное время"),
                ],
                default="none",
                max_length=20,
                verbose_name="Уведомление",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurrences",
                to="planner.task",
                verbose_name="Родительская задача",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Повторять до"),
        ),
        migrations.AddField(
            model_name="task",
            name="weekly_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Дни недели для повторения (0-6, где 0 - понедельник)",
                verbose_name="Дни недели",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["user", "due_date"], name="planner_tas_user_id_73a774_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["user", "status"], name="planner_tas_user_id_09183e_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="planner_tas_due_dat_0e83de_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["parent_task"], name="planner_tas_parent__a65fc2_idx"),
        ),
        migrations.AddField(
            model_name="notification",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="planner.task",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_read"], name="planner_not_user_id_723a7c_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["scheduled_for", "is_sent"], name="planner_not_schedul_e7ed7c_idx"),
        ),
    ]
